# Firefox on X11
dot_desktop_path = "/usr/share/applications/firefox.desktop"
gtk_application = true

[import_conf]
copy = [".mozzila"]

[config]
executable_name = "/usr/bin/firefox"
services = ["x11", "network", "pulse_audio",]

[config.service.home_share]
home_paths = [ "Downloads",]