# Firefox on X11
dot_desktop_path = "/usr/share/applications/firefox.desktop"
is_gtk_application = true

#[import_conf]
#copy = [".mozilla"]

[services]
[services.common]
executable_name = "/usr/bin/firefox"
[services.x11]
[services.network]
[services.pulse_audio]
[services.notify]

[services.home_share]
home_paths = [ "Downloads",]