dot_desktop_path = "/usr/share/applications/net.lutris.Lutris.desktop"

[services.common]
executable_name = "/usr/bin/lutris"

[services.x11]
[services.network]
[services.direct_rendering]
[services.pulse_audio]
[services.joystick]
[services.openjdk]
