
dot_desktop_path = "/usr/share/applications/steam.desktop"

[services.common]
executable_name = "/usr/bin/steam"

[services.x11]
[services.pulse_audio]
[services.network]
[services.direct_rendering]
[services.joystick]
[services.root_share]
