# Modified from CodeQL file
---
name: "Python (mypy, flake8)"

on:
  workflow_dispatch:
  push:
    paths:
      - 'bubblejail/*.py'
      - 'test/*.py'
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 18 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          # Use 3.9 since it is what Arch packages at the moment

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install flake8 and mypy
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy tomli tomli-w

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Lint with mypy
        run: |
          mypy --strict --ignore-missing-imports .
